### ISSUE TITLE
Tools installed by the deployment script don't work with the generated files

### ISSUE THREAD

**Issue by philippgille** [backmeupplz/fondu#11]
`deploy.sh` does for example `npm install -g truffle`, which installs the latest truffle version. But the latest truffle version comes with a newer web3 version than the one used in the `createRealAccount.js` for example.
Or the contracts are for Solidity `0.4.24`, but the installed `solc` is `0.5.something`.

You should *either* run your tools with freshly generated contracts (generated by fondu.io), check what works and what doesn't and change everything so it works again.  
*Or* make all scripts and configs so that they use a fixed version that will also work in a year, even if it's not the latest version in a year anymore (for example, with `truffle-config.js` containing the following, `solc 0.4.24` will be used by default:
```
compilers: {
    solc: {
      version: "0.4.24"
    }
},
```
)

**Comment by philippgille** [comment]
Another option would be to provider a Docker image with all the right dependencies and tools installed, so only the generated contract files would have to be volume mapped into the container and that's it. That would actually be the easiest solution.

**Comment by backmeupplz** [comment]
I'll probably just update the dependencies, installing Docker for such a small script might be an overkill for a general user

**Comment by backmeupplz** [comment]
Looks like I've fixed it. Thank you for the report!
