### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [backmeupplz/fondu#12]
Hi,

is Fondu can be used/modified to make smartcontract with my own blockchain?

Thanks

**Comment by backmeupplz** [comment]
Hey there, sorry, Fondu is intended to be used by developers who already know what they are doing :)

**Comment by ROBERT-MCDOWELL** [comment]
I'm a developer since 22 years now, I'm newbie about blockchain. so if you think answer to a question like that is smart I don't think it's a good behavior.
