### ISSUE TITLE
Bash deploy.sh 

### ISSUE THREAD

**Issue by emyfops** [backmeupplz/fondu#13]
Hello there, i was currently making my smart contract on my ethereum network and got this error
`deploy.sh: 11: Syntax error: "(" unexpected`

```#!/bin/bash

# Get options
testrpc=true
staging=false
release=false
dry=false

PS3="What blockchain would you like to deploy to?
"
options=("Local blockchain (testrpc)" "Ethereum testnet" "Ethereum mainnet" "Dry run (no deploy)")

**Comment by backmeupplz** [comment]
Hey there! Thank you for the report. We are currently rebuilding Fondu, stay tuned.
